version: '3'
services:
  
  league:
    image: hitalos/laravel:latest
    container_name: league
    env_file: .env
    ports:
      - 8888:80
    volumes:
      - ./:/var/www
    environment:
      DB_HOST: mysql
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
